### ISSUE TITLE
Error: 'Cannot find module node:util'

### ISSUE THREAD

**Issue by burtek** [microsoft/vscode-eslint#1780]
Since upgrading to 2.4.4 error about not being able to find `node:util` pops out.

Node 14.17.1
eslint 7.13.0

**Comment by dbaeumer** [comment]
node:util requires node 16 or above. Node 14 is quite old so I would recommend to either upgrade Node or to move to version 2.4.2 of the extension.

**Comment by burtek** [comment]
Sure, will pin 2.4.2 for now. Can't upgrade node just yet. I just thought it's a bug, I'd expect a breaking change (dropping support for node version) to be a major version bump. Hopefully we can upgrade to node 18 soon.
