### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined

### ISSUE THREAD

**Issue by raksa** [microsoft/vscode-eslint#713]
(node:2850) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/Users/raksa/.vscode/extensions/dbaeumer.vscode-eslint-1.9.0/server/out/eslintServer.js:1:47836)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2850) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2850) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/Users/raksa/.vscode/extensions/dbaeumer.vscode-eslint-1.9.0/server/out/eslintServer.js:1:47836)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by dbaeumer** [comment]
@raksa do you have any steps how to reproduce this. Do you have a GitHub repository I can clone that demos this?

**Comment by raksa** [comment]
hi @dbaeumer  you can follow clone and follow the step in README.md
the repo https://github.com/raksa/eslint_error

<img width="1026" alt="Screen Shot 2019-07-12 at 11 22 49 PM" src="https://user-images.githubusercontent.com/4116021/61143341-24f10580-a4fc-11e9-9706-56bfad9053cc.png">

hope you can catch the bug, thanks

**Comment by krutoo** [comment]
I have same issue with ESLint 6.1.0 and VSCode 1.36.1

**Comment by raksa** [comment]
bug with **eslint@6.1.0**

**Comment by krutoo** [comment]
@raksa But for me its not worked with 6.1.0 and works with 6.0.0

**Comment by Lokilicious** [comment]
@raksa Not working with 6.1.0

**Comment by raksa** [comment]
VSCode Version 1.36.1 (1.36.1)
Eslint Version 6.1.0
VSCode ESLint Extension version 1.9.0
Working for now

<img width="1280" alt="Screen Shot 2019-08-06 at 3 05 48 PM" src="https://user-images.githubusercontent.com/4116021/62532419-8479d100-b86e-11e9-92dd-6ef7ee00edd3.png">

**Comment by Lokilicious** [comment]
I am running with exactly the same versions and still cannot get it to work

![version](https://user-images.githubusercontent.com/15230279/62534079-85980780-b848-11e9-81ee-8fe8973aad02.png)

**Comment by Lokilicious** [comment]
@dbaeumer @raksa in my opinion this is not fixed yet, the example code provided by @raksa is still giving me the same error. 

For eslint version 6.0.0 and 6.0.1 as well.

Please reopen.

**Comment by dbaeumer** [comment]
Actually even eslint fails when executed in the terminal.

```
bugs\eslint\eslint_error [master ≡ +1 ~0 -0 !]> .\node_modules\.bin\eslint .\index.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'acorn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\eslint_error\node_modules\acorn-jsx\index.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

So I think that this is a problem with ESLint itself, however I agree that the error message should be better in the extension.

**Comment by dbaeumer** [comment]
Improved ESLint extension to print the additional information to the Output panel. You now get

```
[Info  - 3:44:52 PM] ESLint server stopped.
Debugger listening on ws://127.0.0.1:6011/e37ff1de-8ee1-40c9-b187-8f4a3dbcdd77
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[Info  - 3:45:10 PM] ESLint server running in node v10.11.0
[Info  - 3:45:10 PM] ESLint server is running.
[Error - 3:45:39 PM] Error: Cannot find module 'acorn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (c:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\eslint_error\node_modules\acorn-jsx\index.js:8:15)
    at Object.<anonymous> (c:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\eslint_error\node_modules\acorn-jsx\index.js:443:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
[Error - 3:45:39 PM] Failed to load eslint library from c:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\eslint_error\node_modules\eslint\lib\api.js. See output panel for more information.

```

**Comment by dbaeumer** [comment]
@raksa I will close the issue again. If you want to see the issue reopened, please explain why.

**Comment by raksa** [comment]
okay when I see the problem reopen and report again, thanks

**Comment by dbaeumer** [comment]
This is fixed internally in the code base, but it requires a new ESLint version. But as always issues get closed when fixed in the code base.

**Comment by dbaeumer** [comment]
And please remember this in your example this is a setup issue of eslint and not a problem with the extension itself.
