### ISSUE TITLE
ruleCreator is not a function

### ISSUE THREAD

**Issue by kevinbarabash** [Microsoft/vscode-eslint#159]
I'm getting the following error message:
```
Error while loading rule 'react/sort-comp': ruleCreator is not a function
```

Here's my .eslintrc:
```
{
    "rules": {
        "indent": [2, 4],
        "quotes": [2, "double"],
        "linebreak-style": [2, "unix"],
        "semi": [2, "always"],
        "react/sort-comp": 2
    },
    "env": {
        "es6": true,
        "browser": true
    },
    "extends": "eslint:recommended",
    "ecmaFeatures": {
        "jsx": true,
        "experimentalObjectRestSpread": true
    },
    "plugins": [
        "react"
    ]
}
```

I'm on 1.0.8 of the eslint plugin and 1.6.1 of vscode.

**Comment by kevinbarabash** [comment]
My global version of eslint was at v1.7.1.  After upgrading it to v3.8.1 the issue resolved itself.
