### ISSUE TITLE
Eslint v6 > eslint.workingDirectories being ignored

### ISSUE THREAD

**Issue by danielcooke1996** [microsoft/vscode-eslint#700]
It seems after upgrading to v6.0.1 of eslint, the `eslint.workingDirectories` config option is being ignored.
```
"eslint.workingDirectories": [
        { 
            "directory" : "./packages/user-interface", 
            "changeProcessCWD": true
        }
    ],
```

We expect the plugin `import/resolver` to point to our webpack config in `packages/user-interface` not at the root `/` level.

```
Error resolving webpackConfig Error: Cannot find module '/Users/dancooke/Projects/my-project-root/next.config.js'
Require stack:`
```

It should be resolving the path from the package, as i've set `changeProcessCWD` to true

**Comment by dbaeumer** [comment]
@danielcooke1996 can you provide me with a GitHub repository that I can clone that shows the problem. I tested it locally and the `workingDirectories` setting still works for me.

**Comment by johnnyreilly** [comment]
I'm afraid I don't have a repro to share at present (apologies - I know that doesn't help you much) but I seem to be bumping on this too

**Comment by danielcooke1996** [comment]
@dbaeumer I will try to get a reproduction repo this week at some point

**Comment by dbaeumer** [comment]
@johnnyreilly have you upgraded to ESLint 6.0. If so you might want to look at: https://github.com/microsoft/vscode-eslint/issues/696

**Comment by dpkirchner** [comment]
@dbaeumer Do you have an example demonstrating workingDirectories? It's not working for me, either, although my exact scenario is different (no errors, it just ignores the .eslintrc files in the specified working directory.

**Comment by dbaeumer** [comment]
@dpkirchner this repository has a working directory setting for its server and client folder.

**Comment by dpkirchner** [comment]
Thanks, that helped me figure out what I was doing wrong.
